enum program_status {program_status_quit, program_status_running, 
program_status_enterprise_menu,
program_status_facility_table, program_status_facility_editor,
program_status_employee_table, program_status_employee_editor,
program_status_item_table, program_status_item_editor,
program_status_customer_table, program_status_customer_editor,};